button_option: stbc_large
comments: 0
late_load: 0
location: content
node_types:
  blog_post: blog_post
  success_story: success_story
  alert: null
  article: null
  event: null
  news: null
  page: null
  partnering_opportunity: null
  quote: null
option_extras:
  'Google Plus One:plusone': '0'
  'Facebook Like:fblike': '0'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '''Facebook:facebook'',''Twitter:twitter'',''Google +:googleplus'',''LinkedIn:linkedin'',''Email:email'''
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  page:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  alert:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  blog_post:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  event:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  news:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  partnering_opportunity:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  quote:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  success_story:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-5dc2f062-8215-1754-179-9f8ec9fcc4e5
callesi: '0'
