page_title: Sitemap
message:
  value: ''
  format: restricted_html
show_front: false
show_titles: true
show_books: {  }
books_expanded: true
show_menus:
  account: account
  footer: footer
  main: main
  admin: '0'
  tools: '0'
  workbench: '0'
show_menus_hidden: false
show_vocabularies:
  event_source: '0'
  tags: '0'
show_description: true
show_count: true
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 1
rss_taxonomy: -1
css: true
order:
  menus_admin: -50
  menus_main: -49
  front: -48
  menus_account: -47
  menus_footer: -46
  vocabularies_event_source: -45
  vocabularies_tags: -44
  menus_tools: -43
  menus_workbench: -42
_core:
  default_config_hash: yUNkiSB-fp4pyUb6B2L9HiiCdISBDvK7r1v9_XkGUaQ
