<?php

function opportunity_search_theme()
{
    return [
        'opportunity_search' => [
            'variables' => [
                'name'      => null,
                'form'      => null,
                'results'   => null,
                'total'     => null,
                'page'      => null,
                'pageTotal' => null,
            ],
            'template'  => 'opportunity-search',
        ],
    ];
}