<?php
function opportunity_search_theme()
{
    return [
        'opportunity_form'    => [
            'variables' => [
                'name'      => null,
                'form'      => null,
                'results'   => null,
                'total'     => null,
                'page'      => null,
                'pageTotal' => null,
            ],
            'template'  => 'opportunity-form',
        ],
        'opportunity_details' => [
            'variables' => [
                'name'        => null,
                'opportunity' => null,
            ],
            'template'  => 'opportunity-details',
        ],
    ];
}