<?php
function events_theme()
{
    return [
        'events_search'  => [
            'variables' => [
                'results'       => null,
                'form'          => null,
                'total'         => 0,
                'page'          => 1,
                'pageTotal'     => 0,
                'resultPerPage' => 10,
                'route'         => 'events.search',
            ],
            'template'  => 'events-search',
        ],
        'events_details' => [
            'variables' => [
                'form'       => null,
                'form_email' => null,
                'event'      => null,
                'page'       => 1,
                'email'      => null,
                'token'      => null,
                'route'      => 'events.search',
            ],
            'template'  => 'events-details',
        ],
        'events_static_details' => [
            'variables' => [
                'form'       => null,
                'form_email' => null,
                'event'      => null,
                'page'       => 1,
                'email'      => null,
                'token'      => null,
                'route'      => 'events.search',
            ],
            'template'  => 'events-details-static',
        ],
    ];
}

/*
 * Get events that have passed and unpublish
 */
function events_cron()
{
    $fids =  \Drupal::entityQuery('node')
        ->condition('type', 'event')
        ->condition('field_event_date.end_value', date("Y-m-d"), '<')
        ->condition('status', 1, '=')
        ->execute();

    foreach($fids as $nid){
        $node = \Drupal\node\Entity\Node::load($nid);
        $node->set("changed", $node->changed->value);
        $node->set("status", '0');
        $node->set("moderation_state", 'archived');
        $node->save();
    }
}