<?php
function opportunities_theme()
{
    return [
        'opportunities_form'    => [
            'variables' => [
                'form'      => null,
            ],
            'template'  => 'opportunities-form',
        ],
        'opportunities_results' => [
            'variables' => [
                'results'   => null,
                'total'     => 0,
                'page'      => 1,
                'pageTotal' => 0,
                'route'     => 'opportunities.results',
            ],
            'template'  => 'opportunities-results',
        ],
        'opportunities_details' => [
            'variables' => [
                'opportunity' => [],
            ],
            'template'  => 'opportunities-details',
        ],
    ];
}