<?php
function opportunities_theme()
{
    return [
        'opportunities_search_test' => [
            'variables' => [
                'form'             => null,
                'search'           => null,
                'opportunity_type' => null,
                'results'          => null,
                'results2'         => null,
                'results3'         => null,
                'total'            => 0,
                'total2'           => 0,
                'total3'           => 0,
                'page'             => 1,
                'pageTotal'        => 0,
                'resultPerPage'    => 10,
                'route'            => 'opportunities.search',
            ],
            'template'  => 'opportunities-search-test',
        ],

        'explore_opportunities' => [
            'variables' => [
                'form'             => null,
                'search'           => null,
                'opportunity_type' => null,
                'results'          => null,
                'results2'         => null,
                'results3'         => null,
                'total'            => 0,
                'total2'           => 0,
                'total3'           => 0,
                'page'             => 1,
                'pageTotal'        => 0,
                'resultPerPage'    => 10,
                'route'            => 'opportunities.explore',
            ],
            'template'  => 'opportunities-sentence-builder',
        ],

        'super_search_opportunities' => [
            'variables' => [
                'form'             => null,
                'search'           => null,
                'opportunity_type' => null,
                'results'          => null,
                'results2'         => null,
                'results3'         => null,
                'total'            => 0,
                'total2'           => 0,
                'total3'           => 0,
                'page'             => 1,
                'pageTotal'        => 0,
                'resultPerPage'    => 10,
                'route'            => 'opportunities.super-search',
            ],
            'template'  => 'opportunities-super-search',
        ],

        'opportunities_search'           => [
            'variables' => [
                'form'             => null,
                'search'           => null,
                'opportunity_type' => null,
                'country'          => null,
                'results'          => null,
                'total'            => 0,
                'page'             => 1,
                'pageTotal'        => 0,
                'resultPerPage'    => 10,
                'form2'             => null,
                'route'            => 'opportunities.search',
            ],
            'template'  => 'opportunities-search',
        ],
        'opportunities_details'          => [
            'variables' => [
                'form'             => null,
                'form_email'       => null,
                'form_login'       => null,
                'opportunity'      => [],
                'search'           => null,
                'opportunity_type' => null,
                'country'          => null,
                'token'            => null,
                'email'            => null,
                'mail'             => null,
            ],
            'template'  => 'opportunities-details',
        ],
        'opportunities_search_temp'      => [
            'variables' => [
                'form'             => null,
                'search'           => null,
                'opportunity_type' => null,
                'results'          => null,
                'results2'         => null,
                'results3'         => null,
                'total'            => 0,
                'total2'           => 0,
                'total3'           => 0,
                'page'             => 1,
                'pageTotal'        => 0,
                'resultPerPage'    => 10,
                'route'            => 'opportunities.search',
            ],
            'template'  => 'opportunities-search-temp',
        ],
        'opportunities_widget'      => [
            'variables' => [
                'form'             => null,
                'search'           => null,
                'opportunity_type' => null,
                'results'          => null,
                'results2'         => null,
                'results3'         => null,
                'total'            => 0,
                'total2'           => 0,
                'total3'           => 0,
                'page'             => 1,
                'pageTotal'        => 0,
                'resultPerPage'    => 10,
                'route'            => 'opportunities.widget',
            ],
            'template'  => 'opportunities-widget',
        ],

    ];
}

function opportunities_preprocess_html(&$variables)
{
    if (\Drupal::request()->getPathInfo() === '/opportunities') {
        $variables['skip_text'] = 'View your search results';
    }
}